# Generated by Django 6.0.6 on 2026-06-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_user_role_customerprofile_farmerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(max_length=10, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='FarmerProfile',
        ),
    ]
